### ISSUE TITLE
Some ops seem exceedingly slow on Apple M2

### ISSUE THREAD

**Issue by karalabe** [ethereum/c-kzg-4844#290]
I wrote an integration today for Geth for both the C and the Go libs. https://github.com/ethereum/go-ethereum/pull/27155

Interestingly, blob to commitmets and proof generations with this lib seem to be 5-6x slower than the pure Go one, which seems be mean that something goes very wrong in compiling the C code: https://github.com/ethereum/go-ethereum/pull/27155#issuecomment-1520781580

Any idea on how to investigate this?

**Comment by asn-d6** [comment]
This might be an issue with the assembly, but in general c-kzg is not really optimized for commitment generation and proof generation. That's because:
- c-kzg does not do multithreading in the multiscalar multiplication, which IIRC go-kzg does
- We did not put much effort into optimizing commitment/proof creation. That was both because of lack of time and also because it's generally slightly harder to do optimizations in C. go-kzg does a bunch of smart caching to avoid expensive divisions etc.
- We also sorta assumed that rollups and anyone who cared about commitment/proof creation would use go-kzg.

**Comment by jtraglia** [comment]
Hey @karalabe. Yes, we expect Go-KZG-4844 to be faster at those things because they are parallelized. If you run the benchmarks with one core, C-KZG should be faster. I mentioned this at the bottom of my comment [here](https://github.com/ethereum/go-ethereum/issues/27047#issuecomment-1496056975).

To be clear, run `GOMAXPROCS=1 go test -bench=.` in Go-KZG-4844.

**Comment by karalabe** [comment]
Well, that's quite a bad practice to do IMO. Concurrency should ideally be done at a higher level, not an an individual crypto peration level that takes millliseconds to complete.

**Comment by karalabe** [comment]
Do you know where that parallelization code is? Can't seem to find it

**Comment by jtraglia** [comment]
So these functions are in the [`prove.go`](https://github.com/crate-crypto/go-kzg-4844/blob/master/prove.go) file. I don't think it's explicitly parallelized (like with the `go` keyword); I think it's just a side-effect of Go executing each function call in a different thread. I don't think it should behave this way by default either.

**Comment by asn-d6** [comment]
> Do you know where that parallelization code is? Can't seem to find it

https://github.com/ConsenSys/gnark-crypto/blob/master/ecc/bls12-381/multiexp.go#L120

**Comment by karalabe** [comment]
Go doesn’t do magic execution. If there’s no ‘go’ keyword, there’s no
parallelization. If gomaxprocs makes a difference, the somewhere deep there
are goroutines.

**Comment by jtraglia** [comment]
Ah yeah, sorry I thought it behaved that way but I'm wrong. I believe @asn-d6 has found the real culprit.

**Comment by karalabe** [comment]
Will run some benchmarks tomorrow, but my gut feeling is that multi
threading at that depth is a performance killer opposed to doing it higher.

**Comment by kevaundray** [comment]
> Well, that's quite a bad practice to do IMO. Concurrency should ideally be done at a higher level, not an an individual crypto peration level that takes millliseconds to complete.

In general I agree -- this algorithm in particular is particularly implemented with parallelism in mind. 

There is a configuration that you can set to tell it how many go-routines to use [here](https://github.com/ConsenSys/gnark-crypto/blob/f93a56c714c4e6266429cac111a004e9eec7daa0/ecc/ecc.go#L118) though I chose to not make it accessible for simplicity and due to the fact that it seemed like it was not needed
