### ISSUE TITLE
Release Rust bindings on crates.io

### ISSUE THREAD

**Issue by DaniPopes** [ethereum/c-kzg-4844#346]
We'd like to use the `c-kzg` bindings in [`revm`](https://github.com/bluealloy/revm). Currently, we would have to import them as a `git` dependency on this repository, but then we will not be able to release the `revm` crates on crates.io ourselves, since `git` dependencies are not allowed: <https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories>.

**Comment by rakita** [comment]
Published crate with newest main to have something there and to unblock us on revm side: https://crates.io/crates/c-kzg
Published from this branch: https://github.com/rakita/c-kzg-4844/tree/publish

Perfectly okay to give ownership to the team in the future.

**Comment by asn-d6** [comment]
My understanding is that if we want to support both minimal and mainnet config, we would need to publish two crates right now. Is this correct?

In this case, https://github.com/ethereum/c-kzg-4844/pull/352 would be a nice improvement, since it would allow us to publish a single crate that can support any config.

**Comment by asn-d6** [comment]
Closing stale tickets. Feel free to reopen if needed.
