### ISSUE TITLE
Remove "-Bsymbolic" compilation requirement from python bindings

### ISSUE THREAD

**Issue by dankrad** [ethereum/c-kzg-4844#81]
Currently the python bindings do not compile on MacOS. It seems like the "-Bsymbolic" compiler option is not available, and without it it's reporting lots of missing python symbols.

Tagging @hwwhww

**Comment by jtraglia** [comment]
Unsure if it can be removed, but it is possible to get this working on macOS (M1 MacBook Air in my experience). The problem is with Apple's version of clang. You can install the other one with brew, it's part of `llvm`.

```
brew install llvm
```

Then add those `llvm` binaries to your path. The installation will tell you the command to run, in my case it was:
```
echo 'export PATH="/opt/homebrew/opt/llvm/bin:$PATH"' >> ~/.zshrc
```

**Comment by xrchz** [comment]
Related: I can confirm that `-Bsymbolic` is not needed on GNU/Linux (x86_64).
